### ISSUE TITLE
Some way to export prior to triangulation?

### ISSUE THREAD

**Issue by andybak** [stefalie/shapeml#2]
I can't see a way as far as I can tell. Obj export is already triangulated and the shape tree contains no polygon data.

I believe Obj actually supports non-triangular faces so maybe it could just be an extra export option to preserve faces with side > 3 ?

**Comment by stefalie** [comment]
Hey,
I just added a branch called `experimental/no-triangulation`. It's not thoroughly tested, but I think it that does what you ask for. There is a new command line option `--export-dont-triangulate` and new checkbox in the GUI (next to the export button) to disable triangulation. By default the triangulation is still on.

I hope this helps.

**Comment by andybak** [comment]
Thanks! That works perfectly.

**Comment by stefalie** [comment]
Cool. I'll close this issue then. If I ever find time to test it a bit more, I'll merge it back to master.
